spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.hibernate.event.internal: TRACE
    org.hibernate.internal.SessionImpl: TRACE